### ISSUE TITLE
Visualization of filter frequency response

### ISSUE THREAD

**Issue by WuJi1** [tuananh0305/End2End_SpeakRecognition_SincNet#2]
I'm very interested to know how you visualize the frequency response in the form of the following figure. 
![image](https://user-images.githubusercontent.com/48046218/148757731-adaaf5b8-4138-4152-b01b-a60d08681b62.png)
I found this figure in your link: https://github.com/mravanelli/SincNet/issues/88
If it's convenient, can you share the visualized code?

**Comment by chang111** [comment]
Hi WuJi1,

Have you got the visualization code?

If so, please share me too.

best
